# Generated by Django 2.2 on 2021-05-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
